name: gdg
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.2
  - pip=24.0
  - cudatoolkit=11.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.25.2
  - matplotlib=3.7.2
  - imageio=2.34.1
  - pip:
    - -e .
